# This is a basic workflow to help you get started with Actions

name: Deploy master (CD)

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    types: [closed]
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Install
        run: npm install
      
      - name: Build
        run: npm run build
        env:
          REACT_APP_GRAPHQL_ENDPOINT: ${{ secrets.REACT_APP_GRAPHQL_ENDPOINT }}
          REACT_APP_GRAPHQL_API_KEY: ${{ secrets.REACT_APP_GRAPHQL_API_KEY }}
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Upload to S3
        run: aws s3 sync ./build/ s3://chriskulwikmusic.com --delete --acl public-read

      - name: Deploy GraphQL Server to Lambda
        run: |
          cd server
          npm install
          zip -r ../server.zip .
          cd ..
          aws lambda update-function-code \
            --function-name music-graphql \
            --zip-file fileb://server.zip \
            --region us-east-2
